-- Replaces the catalogue with the supplied spreadsheet.
-- Previous contents backed up to
-- supabase/backups/products-before-import-2026-09-29.json

delete from public.product_variants;
delete from public.products;

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('24-care-ultra-anti-bacterial-xl-8-pads', '24 Care Ultra Anti Bacterial XL+ 8 Pads', 'Sanitary napkins from 24 Care, 8 Pads per pack, 280mm length.', '{}', '{}', '/images/products/24-care-ultra-anti-bacterial-xl-8-pads-sq.jpg', 'own_brand', true, false, 1, (select id from public.brands where slug = '24care'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '24-care-ultra-anti-bacterial-xl-8-pads'), '280mm', '8 Pads', 'SKU026', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('24-care-ultra-anti-bacterial-xxl-40-pads', '24 Care Ultra Anti Bacterial XXL+ 40 Pads', 'Sanitary napkins from 24 Care, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/24-care-ultra-anti-bacterial-xxl-40-pads-sq.jpg', 'own_brand', true, false, 2, (select id from public.brands where slug = '24care'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '24-care-ultra-anti-bacterial-xxl-40-pads'), '320mm', '40 Pads', 'SKU027', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-1-pieces', '7 Soft Baby Diaper Pants - (1 Pieces)', 'Pant-style baby diapers from 7 Soft, 1 Pcs per pack, available in Small, Medium and Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-1-pieces-sq.jpg', 'own_brand', true, false, 3, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-1-pieces'), 'Small', '1 Pcs', 'SKU001', 'in_stock', 1);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-1-pieces'), 'Medium', '1 Pcs', 'SKU002', 'in_stock', 2);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-1-pieces'), 'Large', '1 Pcs', 'SKU003', 'in_stock', 3);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-24-pieces', '7 Soft Baby Diaper Pants - (24 Pieces)', 'Pant-style baby diapers from 7 Soft, 24 Pcs per pack, size Extra Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-24-pieces-sq.jpg', 'own_brand', true, false, 4, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-24-pieces'), 'Extra Large', '24 Pcs', 'SKU007', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-30-pieces', '7 Soft Baby Diaper Pants - (30 Pieces)', 'Pant-style baby diapers from 7 Soft, 30 Pcs per pack, size Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-30-pieces-sq.jpg', 'own_brand', true, false, 5, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-30-pieces'), 'Large', '30 Pcs', 'SKU006', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-34-pieces', '7 Soft Baby Diaper Pants - (34 Pieces)', 'Pant-style baby diapers from 7 Soft, 34 Pcs per pack, size Medium.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-34-pieces-sq.jpg', 'own_brand', true, false, 6, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-34-pieces'), 'Medium', '34 Pcs', 'SKU005', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-40-pieces', '7 Soft Baby Diaper Pants - (40 Pieces)', 'Pant-style baby diapers from 7 Soft, 40 Pcs per pack, size Small.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-40-pieces-sq.jpg', 'own_brand', true, false, 7, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-40-pieces'), 'Small', '40 Pcs', 'SKU004', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-50-pieces', '7 Soft Baby Diaper Pants - (50 Pieces)', 'Pant-style baby diapers from 7 Soft, 50 Pcs per pack, available in Small, Medium and Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-50-pieces-sq.jpg', 'own_brand', true, false, 8, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-50-pieces'), 'Small', '50 Pcs', 'SKU008', 'in_stock', 1);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-50-pieces'), 'Medium', '50 Pcs', 'SKU009', 'in_stock', 2);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-50-pieces'), 'Large', '50 Pcs', 'SKU010', 'in_stock', 3);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-56-pieces', '7 Soft Baby Diaper Pants - (56 Pieces)', 'Pant-style baby diapers from 7 Soft, 56 Pcs per pack, size Extra Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-56-pieces-sq.jpg', 'own_brand', true, false, 9, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-56-pieces'), 'Extra Large', '56 Pcs', 'SKU014', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-62-pieces', '7 Soft Baby Diaper Pants - (62 Pieces)', 'Pant-style baby diapers from 7 Soft, 62 Pcs per pack, size Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-62-pieces-sq.jpg', 'own_brand', true, false, 10, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-62-pieces'), 'Large', '62 Pcs', 'SKU013', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-72-pieces', '7 Soft Baby Diaper Pants - (72 Pieces)', 'Pant-style baby diapers from 7 Soft, 72 Pcs per pack, size Medium.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-72-pieces-sq.jpg', 'own_brand', true, false, 11, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-72-pieces'), 'Medium', '72 Pcs', 'SKU012', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-75-pieces', '7 Soft Baby Diaper Pants - (75 Pieces)', 'Pant-style baby diapers from 7 Soft, 75 Pcs per pack, available in Small, Medium and Large.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-75-pieces-sq.jpg', 'own_brand', true, false, 12, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-75-pieces'), 'Small', '75 Pcs', 'SKU047', 'in_stock', 1);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-75-pieces'), 'Medium', '75 Pcs', 'SKU048', 'in_stock', 2);
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-75-pieces'), 'Large', '75 Pcs', 'SKU049', 'in_stock', 3);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-baby-diaper-pants-78-pieces', '7 Soft Baby Diaper Pants - (78 Pieces)', 'Pant-style baby diapers from 7 Soft, 78 Pcs per pack, size Small.', '{}', '{}', '/images/products/7-soft-baby-diaper-pants-78-pieces-sq.jpg', 'own_brand', true, false, 13, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'baby-diapers'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-baby-diaper-pants-78-pieces'), 'Small', '78 Pcs', 'SKU011', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-care-xl-6-pads-blue', '7 Soft Maxi Care (XL) 6 Pads ( Blue )', 'Sanitary napkins from 7 Soft, 6 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-care-xl-6-pads-blue-sq.jpg', 'own_brand', true, false, 14, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-care-xl-6-pads-blue'), '280mm', '6 Pads', 'SKU030', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-cottony-care-xxl-40-pads', '7 Soft Maxi Cottony Care (XXL) 40 Pads', 'Sanitary napkins from 7 Soft, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/7-soft-maxi-cottony-care-xxl-40-pads-sq.jpg', 'own_brand', true, false, 15, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-cottony-care-xxl-40-pads'), '320mm', '40 Pads', 'SKU036', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-l-6-pads', '7 Soft Maxi Dry (L) 6 Pads', 'Sanitary napkins from 7 Soft, 6 Pads per pack, 235mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-l-6-pads-sq.jpg', 'own_brand', true, false, 16, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-l-6-pads'), '235mm', '6 Pads', 'SKU028', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-xl-18-pads-blue', '7 Soft Maxi Dry (XL) 18 Pads ( Blue )', 'Sanitary napkins from 7 Soft, 18 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-xl-18-pads-blue-sq.jpg', 'own_brand', true, false, 17, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-xl-18-pads-blue'), '280mm', '18 Pads', 'SKU035', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-xl-18-pads-orange', '7 Soft Maxi Dry (XL) 18 Pads ( Orange )', 'Sanitary napkins from 7 Soft, 18 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-xl-18-pads-orange-sq.jpg', 'own_brand', true, false, 18, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-xl-18-pads-orange'), '280mm', '18 Pads', 'SKU033', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-xl-18-pads-purple', '7 Soft Maxi Dry (XL) 18 Pads (Purple)', 'Sanitary napkins from 7 Soft, 18 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-xl-18-pads-purple-sq.jpg', 'own_brand', true, false, 19, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-xl-18-pads-purple'), '280mm', '18 Pads', 'SKU034', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-xl-6-pads-orange', '7 Soft Maxi Dry (XL) 6 Pads ( Orange )', 'Sanitary napkins from 7 Soft, 6 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-xl-6-pads-orange-sq.jpg', 'own_brand', true, false, 20, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-xl-6-pads-orange'), '280mm', '6 Pads', 'SKU029', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-maxi-dry-xl-6-pads-purple', '7 Soft Maxi Dry (XL) 6 Pads (Purple)', 'Sanitary napkins from 7 Soft, 6 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-maxi-dry-xl-6-pads-purple-sq.jpg', 'own_brand', true, false, 21, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-maxi-dry-xl-6-pads-purple'), '280mm', '6 Pads', 'SKU031', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-ultra-cottony-care-xxl-40-pads', '7 Soft Ultra Cottony Care (XXL) 40 Pads', 'Sanitary napkins from 7 Soft, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/7-soft-ultra-cottony-care-xxl-40-pads-sq.jpg', 'own_brand', true, false, 22, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-ultra-cottony-care-xxl-40-pads'), '320mm', '40 Pads', 'SKU037', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('7-soft-ultra-dry-xl-6-pads', '7 Soft Ultra Dry (XL) 6 Pads', 'Sanitary napkins from 7 Soft, 6 Pads per pack, 280mm length.', '{}', '{}', '/images/products/7-soft-ultra-dry-xl-6-pads-sq.jpg', 'own_brand', true, false, 23, (select id from public.brands where slug = '7soft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = '7-soft-ultra-dry-xl-6-pads'), '280mm', '6 Pads', 'SKU032', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-soft-maxi-care-2xl-40-pads-purple', 'Extra Soft Maxi Care-(2XL) 40 Pads (purple)', 'Sanitary napkins from Extra Soft, 40 Pads per pack, 280mm length.', '{}', '{}', '/images/products/extra-soft-maxi-care-2xl-40-pads-purple-sq.jpg', 'own_brand', true, false, 24, (select id from public.brands where slug = 'extrasoft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-soft-maxi-care-2xl-40-pads-purple'), '280mm', '40 Pads', 'SKU040', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-soft-maxi-care-3xl-40-pads-pink', 'Extra Soft Maxi Care-(3XL) 40 Pads (Pink)', 'Sanitary napkins from Extra Soft, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/extra-soft-maxi-care-3xl-40-pads-pink-sq.jpg', 'own_brand', true, false, 25, (select id from public.brands where slug = 'extrasoft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-soft-maxi-care-3xl-40-pads-pink'), '320mm', '40 Pads', 'SKU042', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-soft-maxi-care-3xl-40-pads-purple', 'Extra Soft Maxi Care-(3XL) 40 Pads (Purple)', 'Sanitary napkins from Extra Soft, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/extra-soft-maxi-care-3xl-40-pads-purple-sq.jpg', 'own_brand', true, false, 26, (select id from public.brands where slug = 'extrasoft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-soft-maxi-care-3xl-40-pads-purple'), '320mm', '40 Pads', 'SKU041', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-soft-maxi-care-xxl-40-10', 'Extra Soft Maxi Care-(XXL) 40+10', 'Sanitary napkins from Extra Soft, 40+10 Pads per pack, 320mm length.', '{}', '{}', '/images/products/extra-soft-maxi-care-xxl-40-10-sq.jpg', 'own_brand', true, false, 27, (select id from public.brands where slug = 'extrasoft'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-soft-maxi-care-xxl-40-10'), '320mm', '40+10 Pads', 'SKU043', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-sure-maxi-care-xxl-40-pads', 'Extra Sure Maxi Care-(XXL) 40 Pads', 'Sanitary napkins from Extra Sure, 40 Pads per pack, 320mm length.', '{}', '{}', '/images/products/extra-sure-maxi-care-xxl-40-pads-sq.jpg', 'own_brand', true, false, 28, (select id from public.brands where slug = 'extrasure'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-sure-maxi-care-xxl-40-pads'), '320mm', '40 Pads', 'SKU038', 'in_stock', 1);

insert into public.products (slug, name, description, features, badges, image_url, catalog_type,  is_active, is_featured, sort_order, brand_id, category_id) values ('extra-sure-maxi-care-xxl-40-10', 'Extra Sure Maxi Care-(XXL) 40+10', 'Sanitary napkins from Extra Sure, 40+10 Pads per pack, 320mm length.', '{}', '{}', '/images/products/extra-sure-maxi-care-xxl-40-10-sq.jpg', 'own_brand', true, false, 29, (select id from public.brands where slug = 'extrasure'), (select id from public.product_categories where slug = 'sanitary-pads'));
insert into public.product_variants (product_id, size_label, pack_count, sku, stock_status, sort_order) values ((select id from public.products where slug = 'extra-sure-maxi-care-xxl-40-10'), '320mm', '40+10 Pads', 'SKU039', 'in_stock', 1);
